name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      e2e-tests:
        runs-on: ubuntu-latest # or macos-latest, windows-latest

        steps:
          - uses: actions/checkout@v2

          - uses: actions/setup-node@v1

          - uses: microsoft/playwright-github-action@v1

          - name: Install dependencies and run tests
            run: npm install && npm test
            - uses: microsoft/playwright-github-action@v1

          - name: Install dependencies and run tests
            run: npm install && npm test

          - uses: actions/upload-artifact@v2
            if: ${{ always() }}
            with:
              name: test-artifacts
              path: path/to/artifacts
          - name: Run Playwright tests
            uses: microsoft/playwright-github-action@v1.5.1
